# Generated by Django 5.1.5 on 2025-03-08 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
    ]
