# Generated by Django 5.1.5 on 2025-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_auto_20250308_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='age_emprunt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='sexe_emprunt',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
    ]
