# Generated by Django 5.1.5 on 2025-04-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_emprunt_age_emprunt_emprunt_sexe_emprunt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Editeur',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='book',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='book',
            name='editeur',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='langue',
        ),
        migrations.RemoveField(
            model_name='book',
            name='nombre_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='date_retour_prevue',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='penalite',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='statut',
        ),
    ]
