# Generated by Django 5.1.5 on 2025-02-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=150)),
                ('date_publication', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='books_images/')),
            ],
        ),
    ]
