# Generated by Django 5.1.5 on 2025-03-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='livre',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
    ]
